"""add

Revision ID: 00231b8c98c3
Revises: 0f6902cc8514
Create Date: 2022-08-28 14:18:35.390722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00231b8c98c3'
down_revision = '0f6902cc8514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('person')
    op.drop_table('address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('adressname', sa.TEXT(length=120), nullable=False),
    sa.Column('person_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('category')
    # ### end Alembic commands ###
