"""added

Revision ID: 0045493d6152
Revises: 68d248a748fc
Create Date: 2022-09-03 15:23:19.739982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0045493d6152'
down_revision = '68d248a748fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('email', sa.VARCHAR(length=150), nullable=True),
    sa.Column('passward', sa.VARCHAR(length=120), nullable=True),
    sa.Column('info', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_user')
    )
    # ### end Alembic commands ###
