"""d

Revision ID: 006669ae0a83
Revises: 5118fe7f0fc9
Create Date: 2022-08-28 18:11:51.029654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006669ae0a83'
down_revision = '5118fe7f0fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category'))
    )
    op.create_table('category_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('info', sa.String(length=120), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_items'))
    )
    op.create_table('navlinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nav_Name', sa.String(length=200), nullable=True),
    sa.Column('nav_URL', sa.String(length=200), nullable=True),
    sa.Column('nav_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_navlinks'))
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productName', sa.String(length=180), nullable=True),
    sa.Column('productPrice', sa.Integer(), nullable=True),
    sa.Column('producutInfo', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product'))
    )
    op.create_table('testimonials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('profession', sa.String(length=200), nullable=True),
    sa.Column('img', sa.String(length=200), nullable=True),
    sa.Column('info', sa.String(length=255), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_testimonials'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testimonials')
    op.drop_table('product')
    op.drop_table('navlinks')
    op.drop_table('category_items')
    op.drop_table('category')
    # ### end Alembic commands ###
