"""added

Revision ID: 2642ba3f321f
Revises: 973f3e1bbb35
Create Date: 2022-09-03 15:25:27.316093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2642ba3f321f'
down_revision = '973f3e1bbb35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('passward', sa.String(length=100), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('email', sa.VARCHAR(length=150), nullable=True),
    sa.Column('passward', sa.VARCHAR(length=100), nullable=True),
    sa.Column('info', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_user')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
