"""d

Revision ID: 2f80f74b7a32
Revises: 2eedd889c129
Create Date: 2022-11-22 00:40:34.737962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f80f74b7a32'
down_revision = '2eedd889c129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enjoy', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enjoy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
