"""d

Revision ID: 5118fe7f0fc9
Revises: 2b7ebaa18ae9
Create Date: 2022-08-28 18:07:40.731143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5118fe7f0fc9'
down_revision = '2b7ebaa18ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testimonials')
    op.drop_table('category')
    op.drop_table('product')
    op.drop_table('navlinks')
    op.drop_table('category_items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('info', sa.VARCHAR(length=120), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('navlinks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nav_Name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('nav_URL', sa.VARCHAR(length=200), nullable=True),
    sa.Column('nav_order', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('productName', sa.VARCHAR(length=180), nullable=True),
    sa.Column('productPrice', sa.INTEGER(), nullable=True),
    sa.Column('producutInfo', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testimonials',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('profession', sa.VARCHAR(length=200), nullable=True),
    sa.Column('img', sa.VARCHAR(length=200), nullable=True),
    sa.Column('info', sa.VARCHAR(length=255), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
