"""d

Revision ID: 551f860bc91c
Revises: 36693490278d
Create Date: 2022-08-28 17:31:44.135399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551f860bc91c'
down_revision = '36693490278d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category_items', type_='foreignkey')
    op.drop_column('category_items', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_items', sa.Column('category_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'category_items', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###
