"""d

Revision ID: 5fbe698c567e
Revises: 4dc4587787ed
Create Date: 2022-08-31 15:07:33.009868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fbe698c567e'
down_revision = '4dc4587787ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('infos', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_items', schema=None) as batch_op:
        batch_op.drop_column('infos')

    # ### end Alembic commands ###
