"""d

Revision ID: 96af4b1f74f2
Revises: 5fbe698c567e
Create Date: 2022-08-31 15:08:59.636710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96af4b1f74f2'
down_revision = '5fbe698c567e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_items', schema=None) as batch_op:
        batch_op.drop_column('infos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('infos', sa.VARCHAR(length=120), nullable=True))

    # ### end Alembic commands ###
