"""added

Revision ID: 973f3e1bbb35
Revises: 0045493d6152
Create Date: 2022-09-03 15:24:35.431966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973f3e1bbb35'
down_revision = '0045493d6152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('passward', sa.String(length=100), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
