"""d

Revision ID: 9c6a10c08e96
Revises: 6a2748314ee2
Create Date: 2022-11-22 12:09:30.221420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6a10c08e96'
down_revision = '6a2748314ee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enjoy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info2', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('info3', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enjoy', schema=None) as batch_op:
        batch_op.drop_column('info3')
        batch_op.drop_column('info2')

    # ### end Alembic commands ###
