"""d

Revision ID: afbe7c159b10
Revises: f66af1e263d4
Create Date: 2022-12-04 17:16:57.041658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afbe7c159b10'
down_revision = 'f66af1e263d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_items', schema=None) as batch_op:
        batch_op.drop_column('info2')

    with op.batch_alter_table('pods_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info2', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pods_items', schema=None) as batch_op:
        batch_op.drop_column('info2')

    with op.batch_alter_table('category_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info2', sa.VARCHAR(length=120), nullable=True))

    # ### end Alembic commands ###
