"""d

Revision ID: d188dbd5e14a
Revises: afbe7c159b10
Create Date: 2022-12-05 19:58:23.202192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd188dbd5e14a'
down_revision = 'afbe7c159b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('time', sa.String(length=200), nullable=True),
    sa.Column('wpLink', sa.String(length=255), nullable=True),
    sa.Column('instaLink', sa.String(length=255), nullable=True),
    sa.Column('map', sa.String(length=255), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shops'))
    )
    op.drop_table('testimonials')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testimonials',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('profession', sa.VARCHAR(length=200), nullable=True),
    sa.Column('img', sa.VARCHAR(length=200), nullable=True),
    sa.Column('info', sa.VARCHAR(length=255), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_testimonials')
    )
    op.drop_table('shops')
    # ### end Alembic commands ###
