"""done

Revision ID: e80a94f44bca
Revises: 949b259e0c98
Create Date: 2022-09-01 00:42:02.448445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e80a94f44bca'
down_revision = '949b259e0c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_img',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], name=op.f('fk_member_img_member_id_member')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_member_img'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_img')
    # ### end Alembic commands ###
